// todo-web/src/views/login/index.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          账号登录
        </h2>
      </div>
      <form class="mt-8 space-y-6" @submit.prevent="handleLogin">
        <div class="rounded-md shadow-sm space-y-4">
          <div>
            <el-input 
              v-model="username" 
              placeholder="用户名" 
              :disabled="loading"
            />
          </div>
          <div>
            <el-input 
              v-model="password" 
              type="password" 
              placeholder="密码" 
              :disabled="loading"
            />
          </div>
        </div>

        <div>
          <el-button 
            type="primary" 
            native-type="submit" 
            class="w-full" 
            :loading="loading"
          >
            {{ loading ? '登录中...' : '登录' }}
          </el-button>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { useUserStore } from '@/stores/user';

const username = ref('');
const password = ref('');
const router = useRouter();
const userStore = useUserStore();

const loading = computed(() => userStore.loading);

const handleLogin = async () => {
  if (!username.value || !password.value) {
    ElMessage.error('用户名和密码不能为空');
    return;
  }

  try {
    // 调用登录API
    await userStore.login({
      username: username.value,
      password: password.value
    });
    
    ElMessage.success('登录成功，正在跳转到首页...');
    
    // 登录成功后跳转到首页
    router.push('/fabric');
  } catch (error: any) {
    // 错误处理已在store中完成
    console.error('登录失败', error);
  }
};
</script>

<style scoped>
.el-button {
  height: 40px;
}
</style>

// todo-table/src/pages/Login.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from '@/hooks/use-auth';
import type { LoginCredentials } from '@/lib/auth';

const Login = () => {
  const [username, setUsername] = React.useState('');
  const [password, setPassword] = React.useState('');
  const navigate = useNavigate();
  const { toast } = useToast();
  const { login, loading } = useAuth();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!username || !password) {
      toast({
        title: "登录失败",
        description: "用户名和密码不能为空",
        variant: "destructive",
      });
      return;
    }

    try {
      // 调用登录API
      const credentials: LoginCredentials = { username, password };
      await login(credentials);
      
      toast({
        title: "登录成功",
        description: "正在跳转到首页...",
      });
      
      navigate('/todo');
    } catch (error) {
      toast({
        title: "登录失败",
        description: error instanceof Error ? error.message : "用户名或密码错误",
        variant: "destructive",
      });
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-md w-full space-y-8">
        <div>
          <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">
            账号登录
          </h2>
        </div>
        <form className="mt-8 space-y-6" onSubmit={handleLogin}>
          <div className="rounded-md shadow-sm space-y-4">
            <div>
              <Input
                type="text"
                placeholder="用户名"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                disabled={loading}
              />
            </div>
            <div>
              <Input
                type="password"
                placeholder="密码"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                disabled={loading}
              />
            </div>
          </div>

          <div>
            <Button type="submit" className="w-full" disabled={loading}>
              {loading ? '登录中...' : '登录'}
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;
